on:
  push:
    branches:
      - main

jobs:
  smoke_test:
    name: Smoke test on ubuntu for python 3.10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install build pytest wheel
      - name: Install nplinker
        run: |
          pip install nplinker
          echo $(command -v install-nplinker-deps)
          cp install-nplinker-deps $(command -v install-nplinker-deps)
          echo -e "the install script is:\n"
          cat $(command -v install-nplinker-deps)
      - name: Install deps
        run: |
          install-nplinker-deps --run-on-github
      - name: Run unit tests
        run: pytest -v
