name: apt

on:
  workflow_dispatch:
    inputs:
      current_version:
        description: 'Current version'
        default: '0.0.1'
        type: string
        required: true


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: |
        echo "Start running"
        [[ -e install-nplinker-deps ]] && echo "install script exist" || echo "Error: script not exist"
        echo "copy install script"
        cp ./install-nplinker-deps /usr/local/bin
        echo "execute install script"
        chmod +x ./install-nplinker-deps
