name: Draft or publish Github release

on:
  workflow_dispatch:
    inputs:
#       current_version:
#         description: 'Current version'
#         default: '0.0.1'
#         type: string
#         required: true
      new_version:
        description: 'New version to release, used for package version, tag name and release title'
        default: '0.0.2'
        type: string
        required: true
      mode:
        description: 'Draft or publish Github release'
        default: "Draft"
        required: true
        type: choice
        options:
          - draft
          - publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Draft a Github release
      if: ${{ inputs.mode == 'draft' }}
      run: |
        gh release create v${{ inputs.new_version }} --draft --title v${{ inputs.new_version }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
